Using an inner class for Session.Actor to have better error
Previously using a bad attribute led to error like the following which are not helpful to understand what's going on

```
AttributeError: 'types.SimpleNamespace' object has no attribute 'name'
```